;
define([], function () {
    //登录注册弹窗
    var modal = ['<!--Modal-->',
        '<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">',
        '    <div class="modal-dialog" role="document">',
        '        <div class="modal-content">',
        '            <div class="modal-body">',
        '                <div>',
        '                    <!-- Nav tabs -->',
        '                    <ul class="nav nav-tabs" role="tablist">',
        '                        <li role="presentation" class="active">',
        '                            <a href="#log" id="logTab" aria-controls="log" role="tab" data-toggle="tab">登录</a></li>',
        '                        <li role="presentation"><a href="#reg" id="regTab" aria-controls="reg" role="tab"',
        '                                                   data-toggle="tab">注册</a></li>',
        '                    </ul>',
        '                    <!-- Tab panes -->',
        '                    <div class="tab-content">',
        '                        <div role="tabpanel" class="tab-pane active" aria-labelledby="log-tab" id="log">',
        '                            <form class="form-horizontal">',
        '                                <div class="form-group">',
        '                                    <label for="logNum" class="col-sm-2 control-label">账号</label>',
        '                                    <div class="col-sm-6">',
        '                                        <input type="text" maxlength="30" class="form-control" id="logNum" placeholder="邮箱/手机号">',
        '                                    </div>',
        '                                    <label class="input-warn col-sm-4" id="logNumWarn" for="logNum"></label>',
        '                                </div>',
        '                                <div class="form-group">',
        '                                    <label for="logPass" class="col-sm-2 control-label">密码</label>',
        '                                    <div class="col-sm-6">',
        '                                        <input type="password" maxlength="20" class="form-control" id="logPass" placeholder="大于6位">',
        '                                    </div>',
        '                                    <label class="input-warn col-sm-4" id="logPassWarn" for="logPass"></label>',
        '                                </div>',
        '                                <div class="form-group" id="vali-login">',
        '                                    <div class="col-sm-4 col-sm-offset-2">',
        '                                        <input type="text" maxlength="4" class="form-control" id="logValiText" placeholder="验证码">',
        '                                    </div>',
        '                                    <img class="col-sm-2 validate-img" style="display:none;cursor: pointer;" id="logValiImg" src="" alt=""/>',
        '                                    <label class="input-warn col-sm-4" id="logValiWarn" for="logPass"></label>',
        '                                </div>',
        '                                <div class="form-group">',
        '                                    <div class="col-sm-offset-2 col-sm-10">',
        '                                        <div class="checkbox">',
        '                                            <label>',
        '                                                <input type="checkbox"> 记住密码',
        '                                            </label>',
        '                                        </div>',
        '                                    </div>',
        '                                </div>',
        '                            </form>',
        '                            <div class="modal-footer">',
        '                                <span class="submit-warn" id="logWarn"></span>',
        '                                <button type="button" id="logBtn" class="btn btn-primary">登录</button>',
        '                                <button type="button" id="logCloseBtn" class="btn btn-default" data-dismiss="modal">关闭',
        '                                </button>',
        '                            </div>',
        '                        </div>',
        '                        <div role="tabpanel" class="tab-pane" aria-labelledby="reg-tab" id="reg">',
        '                            <form class="form-horizontal">',
        '                                <div class="form-group">',
        '                                    <label for="logNum" class="col-sm-2 control-label">账号</label>',
        '                                    <div class="col-sm-6">',
        '                                        <input type="text" maxlength="30" class="form-control" id="regNum" placeholder="邮箱/手机号">',
        '                                    </div>',
        '                                    <label class="input-warn col-sm-4" id="regNumWarn" for="logNum"></label>',
        '                                </div>',
        '                                <div class="form-group">',
        '                                    <label for="logPass" class="col-sm-2 control-label">密码</label>',
        '                                    <div class="col-sm-6">',
        '                                        <input type="password" maxlength="20" class="form-control" id="regPass" placeholder="大于6位">',
        '                                    </div>',
        '                                    <label class="input-warn col-sm-4" id="regPassWarn" for="logPass"></label>',
        '                                </div>',
        '                                <div class="form-group" id="vali-reg">',
        '                                    <div class="col-sm-4 col-sm-offset-2">',
        '                                        <input type="text" maxlength="4" class="form-control" id="regValiText" placeholder="验证码">',
        '                                    </div>',
        '                                    <img class="col-sm-2 validate-img" style="display:none;cursor: pointer;" id="regValiImg" src="" alt=""/>',
        '                                    <label class="input-warn col-sm-4" id="regValiWarn" for="logPass"></label>',
        '                                </div>',
        '                            </form>',
        '                            <div class="modal-footer">',
        '                                <span class="submit-warn" id="regWarn"></span>',
        '                                <button type="button" id="regBtn" class="btn btn-primary">注册</button>',
        '                                <button type="button" id="regCloseBtn" class="btn btn-default" data-dismiss="modal">关闭</button>',
        '                            </div>',
        '                        </div>',
        '                    </div>',
        '                </div>',
        '            </div>',
        '        </div>',
        '    </div>',
        '</div>'].join("");

    (function insertModal(){
        $('body').prepend(modal);
    })();
});